title: 'Pod 23.APR.PREP.1'
email: fellowship@mlh.io
description: >- # this means to ignore newlines until "baseurl:"
  This is my portfolio website!
baseurl: '/'
url: '/'
twitter_username: mlhacks
github_username: mlh-fellowship

sass:
  sass_dir: _sass

collections:
  fellows:
    output: true

icon: /assets/img/icon.jpg
